Update menu dbms

diff --git a/menu dbms b/menu dbms
--- a/menu dbms
+++ b/menu dbms
@@ -1,42 +1,73 @@
 #!/bin/bash
 
 #functions dbms
+readonly DBS="databases";
 
+function createDB {
+	read -p "Enter Database Name : " dbName;
+	if [[ ! -d $DBS/$dbName ]];
+		then  sudo mkdir $DBS/$dbName;
+				if [[ $? -eq 0 ]]; then
+					echo $dbName" Database Created Successfully" ;
+				else	
+					echo "Error Done While Creating the Database" ;
+				fi
+	else	
+		echo "This Database is Exists";
+	fi
 
+}
+function dropDB {
+  read -p "Enter Database Name : " dbName;
+  sudo rm -r $DBS/$dbName 
+  if [[ $? == 0 ]];
+   then
+    echo "Database Dropped Successfully"
+  else
+    echo "Database Not found"
+  fi
+ 
+}
 
 #function show menu
 show_menus() {
-	clear
+	
 	echo "~~~~~~~~~~~~~~~~~~~~~"	
 	echo " D B M S- M E N U"
 	echo "~~~~~~~~~~~~~~~~~~~~~"
-	echo "1. Create Table"
-	echo "2. Alter Table"
-	echo "3. Add Record"
-	echo "4. Edit Records"
-	echo "5. Delete Records"
-	echo "6. Select Records" 
-        echo "7. Display Table"
-	echo "8. Sort Table"
-	echo "9. Drop Table" 
-	echo "10. Exit"
+        echo "1. Create Database"
+	echo "2. List Datebases"
+	echo "3. Drop Datebase"
+	echo "4. Create Table"
+	echo "5. Alter Table"
+	echo "6. Add Record"
+	echo "7. Edit Records"
+	echo "8. Delete Records"
+	echo "9. Select Records" 
+        echo "10. Display Table"
+	echo "11. Sort Table"
+	echo "12. Drop Table" 
+	echo "13. Exit"
 }
 
 #function read
 read_options(){
 	local choice
-	read -p "Enter choice [ 1 - 10 ] " choice
+	read -p "Enter choice [ 1 - 13 ] " choice
 	case $choice in
-		1) ;;
-		2) ;;
-		3) ;;
+		1)createDB;;
+		2)ls $DBS;;
+		3)dropDB;;
 		4) ;;
 		5) ;;
 		6) ;;
-    7) ;;
+                7) ;;
 		8) ;;
 		9) ;;
-		10) exit 0;;
+		10) ;;
+		11) ;;
+		12);;
+		13) exit 0;;
 		*) echo "error"
 	esac
 }
@@ -47,3 +78,4 @@ do
 	show_menus
 	read_options
 done
+
